export const PROJECTS = [
  {
    title: "Unsplash",
    code: "https://github.com/leoikeh99/unsplash-collection",
    description: "Unsplash clone",
    image: "/projects/unsplash.png",
    live: "https://unsplash-collection-taupe.vercel.app",
    techStack: [
      "TYPESCRIPT",
      "REACTJS",
      "SHADCN",
      "MONGODB",
      "PRISMA ORM",
      "NEXTAUTH",
      "NEXTAUTH",
    ],
  },
  {
    title: "Dev Links",
    description: "Showcase your online presence in one place.",
    image: "/projects/devlinks.png",
    live: "https://link-sharing-app-three.vercel.app/",
    code: "https://github.com/leoikeh99/link-sharing-app/",
    techStack: [
      "TYPESCRIPT",
      "REACTJS",
      "TAILWIND CSS",
      "NEXTJS",
      "PRISMA ORM",
      "MONGODB",
    ],
  },
  {
    title: "Audiophile",
    description: "E-commerce audiophile gear.",
    image: "/projects/audiophile.png",
    live: "https://audiophile-gamma.vercel.app/",
    code: "https://github.com/leoikeh99/audiophile",
    techStack: [
      "NEXTJS",
      "STYLED-COMPONENTS",
      "FRAMER MOTION",
      "FORMIK",
      "JAVASCRIPT",
    ],
  },
  {
    title: "TIC-TAC-TOE online multiplayer game",
    description: "Online multiplayer tic-tac-toe.",
    image:
      "https://res.cloudinary.com/wazza99/image/upload/v1674649040/tictactoe_mblhap.png",
    live: "https://tic-tac-toe-ma15.onrender.com",
    code: "https://github.com/leoikeh99/tic-tac-toe-online",
    techStack: [
      "STYLED-COMPONENTS",
      "WEBSOCKETS",
      "JAVASCRIPT",
      "REACTJS",
      "NODEJS",
    ],
  },
  {
    title: "World Ranks",
    description: "Country information app.",
    image: "/projects/world-ranks.png",
    live: "https://world-ranks-sable.vercel.app/",
    code: "https://github.com/leoikeh99/world-ranks",
    techStack: ["TYPESCRIPT", "REACTJS", "TAILWIND CSS"],
  },
  {
    title: "Dictionary app",
    description: "Online dictionary app.",
    image: "/projects/dictionary.png",
    live: "https://joyful-chebakia-d3a599.netlify.app/",
    code: "https://github.com/leoikeh99/dictionary-app",
    techStack: ["CSS3", "JAVASCRIPT", "REACTJS", "STYLED-COMPONENTS"],
  },
];
